baseURL = "https://andresguzco.github.io/"
languageCode = "en-us"
title = "Andrés Guzmán-Cordero"

copyright = "&copy; 2026 Andrés Guzmán-Cordero. All rights reserved."

[params]
  mainSections = ["posts"]

  [params.head]
    author = "Andrés Guzmán-Cordero"
    description = "Andrés Guzmán-Cordero — PhD student at Mila working on generative modelling for molecular simulation."
    keywords = ["Andrés Guzmán-Cordero", "machine learning", "generative modelling", "molecular simulation", "Mila"]

  [params.navigation]
    show_navigation = true

  [params.footer]
    show_footer = true

  [params.typography]
    title_font = "Space Mono"
    body_font = "Space Mono"

  [params.colors]
    theme_color = "#333333"
    background_color = "#fcfbf9"
    text_color = "#333333"
    link_color = "#60c17d"

  [params.social]
    [params.social.email]
      name = "E-Mail"
      class = "fas fa-envelope"
      url = "mailto:andres.guzman-cordero@mila.quebec"
      weight = 1
    [params.social.github]
      name = "GitHub"
      class = "fab fa-github"
      url = "https://github.com/andresguzco"
      weight = 2
    [params.social.google_scholar]
      name = "Google Scholar"
      class = "ai ai-google-scholar-square"
      url = "https://scholar.google.com/citations?user=mQI7UcgAAAAJ&hl=en"
      weight = 3

[[menus.main]]
  name = "About"
  url = "/about/"
  weight = 1

[[menus.main]]
  name = "Papers"
  url = "/papers/"
  weight = 2

[[menus.main]]
  name = "Posts"
  url = "/posts/"
  weight = 3

[module]
  [module.hugoVersion]
    extended = true
    min = "0.128.0"
